apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: myapp
  labels:
    app: final-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: final-project